language: node_js
cache: yarn
before_install:
- npm install -g yarn --cache-min "999999999"
node_js:
- '7'
install:
- yarn
deploy:
  provider: npm
  email: jacklam718@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: jacklam718/react-date-picker
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: storybook-static
  github_token: $GITHUB_TOKEN
  on:
    branch: master
